### ISSUE TITLE
Add PlanBetter Pool to `Stack using a service`

### ISSUE THREAD

**Issue by diego-G** [blockstack/stacks.co#28]
Planbetter competitive advantages:

- BTC payouts (every cycle)
- low fees (5%)
- low minimum (200 STX)
- ease of use

Website : https://planbetter.org/

![planbetter-logo](https://user-images.githubusercontent.com/1387244/111799398-44dced00-88cb-11eb-9b3a-0bc39664301a.png)

**Comment by markmhx** [comment]
Added!

![image](https://user-images.githubusercontent.com/28991/111833728-dca20180-88f2-11eb-979a-e779a7b8f41e.png)
