### ISSUE TITLE
Migrate FAQ wallet content to status page and redirect

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks.co#3]
All relevant content found on [this FAQ](https://www.hiro.so/questions/what-known-issues-are-currently-affecting-the-stacks-wallet) should be migrated to [the new Stacks.co status page](http://stacks.co/status). Then this FAQ path should redirect permanently to the status page.

**Comment by GinaAbrams** [comment]
@markmhx can you confirm we want to add the copy for both (2) and (3) listed under that FAQ here?

**Comment by markmhx** [comment]
I think we can actually remove #2 and #3 entirely, the former because it's been resolved for awhile now and the latter since we've actually not received any external reports of this yet (just seen it a few times internally) so we're probably safe downgrading its prominence.

It appears that only some version of #1 remains needed.

**Comment by markmhx** [comment]
Also, you should have the ability to add a 301 Redirect [here](https://webflow.com/dashboard/sites/www-blockstack-d63682afc5326964230c5494/hosting?ref=hosting_tab_switch&sp=project%20general%20tab) but let me know if you'd like assistance. Note that you'll need to publish the site again once selecting "Add Redirect Path" there for it to take effect.

**Comment by GinaAbrams** [comment]
I was using the wallet yesterday and there was a warning about Ledger not working properly. Should we remove that too if we're not listing any ledger problems in known issues, or which one is true?

**Comment by markmhx** [comment]
Yea probably. Mind providing a screenshot of what you saw? I'm not sure where we're showing that these days.
