### ISSUE TITLE
Add Neptune to Stacks.co "Wallets" and "Stacking" sections

### ISSUE THREAD

**Issue by ehalekote** [blockstack/stacks.co#31]
**Wallet Section:**
Neptune Wallet
"Non-custodial web wallet"
website: https://neptunewallet.io/

**Stacking Section:**
Neptune Stacking Pool
Instant Rewards Stacking Pool
website: https://neptunewallet.io/

![neptune](https://user-images.githubusercontent.com/6953004/112903380-099da380-90ad-11eb-9570-4947e2113b98.png)

**Comment by markmhx** [comment]
Added!

![image](https://user-images.githubusercontent.com/28991/113684446-89d39280-96c5-11eb-8a7e-a49005be9a12.png)

![image](https://user-images.githubusercontent.com/28991/113684476-8fc97380-96c5-11eb-9ac4-f1e3573ef2f6.png)
